### ISSUE TITLE
Design of Landing Page

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#10]
[https://www.figma.com/file/nUnclpNeBdBXMZ7uYS9UCe/Chunkr.iO?node-id=3%3A9](url)

Due by 24th July, 2022

**Comment by Aadeifee** [comment]
Done

**Comment by U-JoJoBear-X** [comment]
Landing page design has been concluded and can be viewed using the admin link or this one: 
https://www.figma.com/file/nUnclpNeBdBXMZ7uYS9UCe/Chunkr.iO?node-id=3%3A9

**Comment by dajyno** [comment]
Great job guys. Marking this as complete now 👍

**Comment by Queennifer** [comment]
Landing Page check
