### ISSUE TITLE
Sign up/Sign In/Reset Password Modals

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#11]
[https://www.figma.com/file/nUnclpNeBdBXMZ7uYS9UCe/Chunkr.iO?node-id=1198%3A1037](url)

Design pop up modals for the above named items

Due by 24th July, 2022

**Comment by U-JoJoBear-X** [comment]
The pop-up modals are now available. The designs have been completed and can be viewed using the parent link. You should find them right beside the landing page.

**Comment by stepha-cell** [comment]
The Authentication modals have been completed

**Comment by dajyno** [comment]
Looks good, pushing to dev team now.

Marking this as completed!

**Comment by Queennifer** [comment]
Done...Also did the redesign
