### ISSUE TITLE
User Dashboard

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#12]
[https://www.figma.com/file/nUnclpNeBdBXMZ7uYS9UCe/Chunkr.iO?node-id=2%3A5](url)

Design user dashboard 

Due by 25th July, 2022

**Comment by dajyno** [comment]
Dashboard pages including user profile modal, file split modal, shared & recent file pages

Due by 1st August, 2022

N/B More team members would be added to this team

**Comment by Mariamjeda** [comment]
Working on it. Should be done soon.

**Comment by dajyno** [comment]
Please check the buttons on the dashboard, it looks a bit different from the style guide

**Comment by trippleme63** [comment]
How different are the buttons, I did a correction adjustment this afternoon.

**Comment by Mariamjeda** [comment]
Which correction again.

**Comment by dajyno** [comment]
lol, Mariam don confuse oo

**Comment by trippleme63** [comment]
@Mariamjeda Don't worry  😂. You doing Awesome.

**Comment by dajyno** [comment]
> @Mariamjeda Don't worry  😂. You doing Awesome. 
> 
> 

My madam at the top! 🙌🏾

**Comment by Mariamjeda** [comment]
🤪

**Comment by Ebulu** [comment]
> 

These things were already designed before you even assigned them o.

**Comment by trippleme63** [comment]
> > 
> 
> These things were already designed before you even assigned them o.

yes. That's due to we had to start using GitHub as our project management tool. So all initial assignments had to be reassigned here.

**Comment by Mariamjeda** [comment]
This github be confusing somebody

**Comment by Ebulu** [comment]
> > > 
> > 
> > 
> > These things were already designed before you even assigned them o.
> 
> yes. That's due to we had to start using GitHub as our project management tool. So all initial assignments had to be reassigned here.

okay

**Comment by Ebulu** [comment]
> This github be confusing somebody

Omo, the confusion no be here.

**Comment by Mariamjeda** [comment]
Lol

**Comment by Mariamjeda** [comment]
I worked on the researching how dashboards look, came up with rough sketches/ wire frames, worked on a low fi design, implemented the side navigation bar so users can have easy access to various pages on the web app. Worked with Chukwuebuka to merge our ideas on the the dashboard design, reworked the design to make sure the appropriate texts were used and spacing was following the 8 point grid system. Also made sure I added the icons we used to the style guide. Created input fields I needed on some of the dashboard pages and added them to the style guide. I worked on other pages of the dashboard, namely the shared files, trash, settings pages. I also worked on the delete confirmation pop up, log out confirmation pop up, list view of the all files  and starred pages, change password page. I also worked to make sure that pages created by other team members on the dashboard team followed  the design aesthetics. Worked on the settings  and FAQ pages with Chidinma.

**Comment by trippleme63** [comment]
I Sketched out and designed Dashboard Lofi and Hifi design alongside @Mariamjeda and @Ebulu.

We worked as a team to design the dashboard with the users front and centre of our every design decision. I designed the profile pop-up, which appears at the top right of the dashboard when the profile is clicked. This profile pop-up shows brief information about the user. For instance, the User Fullname with registered email and underneath the full name, you will see statistics showing the total number of files split based on the file format. There is also the section of the profile which takes the users to a privacy policy and terms of use page. 

I designed the storage indicator and included a manage button in the lower section of the Dashboard Menu. This button allows users easily format their entire storage. It functions as a way for users to manage their limited space as there isn't an option to upgrade or increase storage at the moment.

Iterated with @Mariamjeda to design the split files folder appearance and designed it in a way it shows users preview information about the folder content like; the number of files in the folder, folder size and most importantly, File name.

I designed the Split File button, Splitting Screen  features and components that support interaction within the dashboard and split screens

**Comment by Ebulu** [comment]
I designed the dashboard lo-fi design together with @Mariamjeda and @trippleme63 . The dashboard was restructured by @Mariamjeda and @trippleme63  at the hi-fi stage. 

I designed the "Dashboard Recent Folder" of the dashboard which allows a user to see a grid view of all the recent files they have worked on. This component also allows the user access to files worked on as far back as the previous year, so long as the files were not purposely deleted by the user. 

I designed the "Dashboard FAQ Folder" of the dashboard. The FAQ on the dashboard guides the user in answering some of the challenges they might face while chunking their files. This is just a sub-section of the main FAQ on the landing page. 

I designed the concept that was used to design the "Settings Folder" of the dashboard alongside @Mariamjeda. This is where the user can change their profile picture, change their password or edit their entire profile as a whole or even log out of their account. I also designed a pop up modal that comes up for the user to confirm if they really want to log out of their account. This  pop up modal helps in cases whereby a user mistakenly clicks on the log out button. 

I designed the "Dashboard Trash Folder". This is where all deleted files are found.

Dashboard Recent Folder Link: https://www.figma.com/file/SJHloBHOZcsHKdhgqb9qGj/WIP-Chunkr.iO?node-id=1808%3A7593

Help & Feedback Link: https://www.figma.com/file/SJHloBHOZcsHKdhgqb9qGj/WIP-Chunkr.iO?node-id=1808%3A7330 

Dashboard Settings Folder: https://www.figma.com/file/SJHloBHOZcsHKdhgqb9qGj/WIP-Chunkr.iO?node-id=2102%3A5446 

Dashboard Trash Folder: https://www.figma.com/file/SJHloBHOZcsHKdhgqb9qGj/WIP-Chunkr.iO?node-id=1808%3A7252 

Dashboard Lo-Fi Design: https://www.figma.com/file/SJHloBHOZcsHKdhgqb9qGj/WIP-Chunkr.iO?node-id=2025%3A4754 

Log Out Pop-Up Modal Link: https://www.figma.com/file/SJHloBHOZcsHKdhgqb9qGj/WIP-Chunkr.iO?node-id=1913%3A4145
