### ISSUE TITLE
Presentation documentation

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#13]
[https://docs.google.com/presentation/d/1CxFb9-kMXlG5jYSg7oPatAzXhhqnygTvjyrZLeWgDRw/edit?usp=sharing](url)

Design of presentation slides and video creation. 

Due by 29th July, 2022

**Comment by Aadeifee** [comment]
Well done guys

**Comment by AyomiCoder** [comment]
i have added my part

**Comment by U-JoJoBear-X** [comment]
I just finished editing the submission video. I've made it available on the slack channel for review. Please check and send a feedback.

**Comment by Queennifer** [comment]
We did good. Well done everyone

**Comment by dajyno** [comment]
Thank you everyone.

Our video is uploaded and the form is filled now. 

Please revert to your pre assigned tasks.

**Comment by Aadeifee** [comment]
Okay boss
Well done

**Comment by AyomiCoder** [comment]
Nice

**Comment by AyomiCoder** [comment]
Completed

**Comment by dajyno** [comment]
> Okay boss
> 
> Well done

Thanks a lot bossette!

**Comment by dajyno** [comment]
Sorry, I didn't add @Mamishayde to this issue earlier.

**Comment by Mamishayde** [comment]
> Sorry, I didn't add @Mamishayde to this issue earlier.

It's okay boss. I worked on the research background, research objectives, idea brief, problem statement and user flow slides.

**Comment by Mamishayde** [comment]
Also provided questions for our FAQs section in our documentation
https://docs.google.com/document/d/1-eNsW_O3NiSakiCxLgsWWwT5Qk4wAgntuHbT76RfLk8/edit#
