### ISSUE TITLE
Documentation/About/FAQ Leader Page 

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#15]
[https://www.figma.com/file/nUnclpNeBdBXMZ7uYS9UCe/Chunkr.iO?node-id=1198%3A1356](url)

Our documentation, FAQ's etc page

Due by 3rd August, 2022

**Comment by U-JoJoBear-X** [comment]
We're done with the low fidelity designs and are currently working on the high fidelity

**Comment by Queennifer** [comment]
Will pick this up today

**Comment by U-JoJoBear-X** [comment]
High fidelity designed has been completed and is ready for review. You can view it using the parent link or check the figma board.

**Comment by dajyno** [comment]
Great job team!

It all looks good. Can we work on the illustration at the top?

**Comment by dajyno** [comment]
> Will pick this up today

Alright sure thing.

**Comment by Busybeebee11** [comment]
WIP by the dev team

**Comment by stepha-cell** [comment]
Great job guys

**Comment by Aadeifee** [comment]
I’ve worked on how to split files, how the tools work and getting started on the page
