### ISSUE TITLE
Our Team Page

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#16]
[https://www.figma.com/file/nUnclpNeBdBXMZ7uYS9UCe/Chunkr.iO?node-id=1198%3A1357](url)

Design of the teams information page.

Due by the 2nd of August, 2022

**Comment by Foluahiome** [comment]
We are working on it

**Comment by dajyno** [comment]
Alright, please center align Jojo's name and info to be in sync with the rest

**Comment by Mamishayde** [comment]
It looks good to me, just to decide on which of the text layout designs we are going for.

**Comment by Mamishayde** [comment]
> Alright, please center align Jojo's name and info to be in sync with the rest

Done, and Chukwuebuka's name also.

**Comment by dajyno** [comment]
We would take a decision on which design to use by tomorrow evening's meeting

**Comment by Mamishayde** [comment]
Alright

**Comment by Foluahiome** [comment]
Ok noted

**Comment by rhodalewi** [comment]
Okay

**Comment by dajyno** [comment]
@Foluahiome @U-JoJoBear-X 
We finalized with the middle option. Fola is also going to move the header and body text immediately under the hero section from frame 1 to frame 2.

**Comment by dajyno** [comment]
Also, please remove the persons no longer on our team @Foluahiome 
Mba, Biodun and Celestine

**Comment by Mamishayde** [comment]
> @Foluahiome @U-JoJoBear-X We finalized with the middle option. Fola is also going to move the header and body text immediately under the hero section from frame 1 to frame 2.

Done

**Comment by Foluahiome** [comment]
@dajyno 

> Also, please remove the persons no longer on our team @Foluahiome Mba, Biodun and Celestine

Done

**Comment by dajyno** [comment]
You're the best ma'am

**Comment by Foluahiome** [comment]
> You're the best ma'am

Just following your lead!

**Comment by Mamishayde** [comment]
@dajyno Please check the comments on the workboard, we need your input/veto power...lolz
https://www.figma.com/file/SJHloBHOZcsHKdhgqb9qGj/WIP-Chunkr.iO?node-id=1198%3A1357

**Comment by dajyno** [comment]
@mamishayde i didnt see anything. Is it the comment about Ofili?

**Comment by Mamishayde** [comment]
I think @Foluahiome and I already resolved it. Thank you. It was about the Eign in/Sign up button position for better UX.
