### ISSUE TITLE
Landing Page - Frontend development

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#17]
Build the landing page, with the navbar that links to the documentation/FAQ page, the signup page should be a pop up modal.

**Comment by dajyno** [comment]
Contents on the webpage must be presented perfectly.

Make it Responsive

**Comment by Busybeebee11** [comment]
Noted. The sign-up page as a pop-up modal is completed.

**Comment by Busybeebee11** [comment]
Nav bar complete. Sign-in and Forgotten pop-up modal completed.

**Comment by Busybeebee11** [comment]
Forgotten password pop-up, good to go.

**Comment by AyomiCoder** [comment]
We should start working on the responsiveness, kudos!

**Comment by adeboluuu** [comment]
left with responsiveness

**Comment by dajyno** [comment]
Great work guys.....really feeling it

**Comment by Busybeebee11** [comment]
landing page and navbar fully responsive

**Comment by dajyno** [comment]
> landing page and navbar fully responsive
> 
> 

Excellent work ma'am

**Comment by Busybeebee11** [comment]
Thanks sir.

**Comment by AyomiCoder** [comment]
@Busybeebee11 please any changes you make on the landing page, add comments on it in the code, so i can render it on the backend too. Thanks🤗

**Comment by Busybeebee11** [comment]
Okay,.
