### ISSUE TITLE
File uploads from the frontend to the backend

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#18]
Get a file uploaded from the frontend to the backend and store in database. 

Django & Mongodb. Research on how to redirect users to the dashboard when they sign up and how to fill up the profile page with the information they provided.

**Comment by exoticmga** [comment]
Great I will drop the codes here or should the share the google Doc link here?

**Comment by exoticmga** [comment]
Task 1: How to bring in a file uploaded from frontend to backend with python and store it in the database. 

Here are block of codes on how to upload a file in Bootstrap
 
                                                  HTML

<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
 
  
<div class="container" style="margin-top: 20px;">
    <div class="row">
        
        <div class="col-lg-6 col-sm-6 col-12">
            <div class="jumbotron">
                <h1>Bootstrap File Input Demo</h1>
            </div>
        </div>
        
        <div class="col-lg-6 col-sm-6 col-12">
            <h4>Standard Button</h4>
            <span class="file-input btn btn-primary btn-file">
                Browse&hellip; <input type="file" multiple>
            </span>
        </div>
        <div class="col-lg-6 col-sm-6 col-12">
            <h4>Block-level Button
            <span class="file-input btn btn-block btn-primary btn-file">
                Browse&hellip; <input type="file" multiple>
            </span>
        </div>
        
        <div class="col-lg-6 col-sm-6 col-12">
            <h4>Button Groups</h4>
            <div class="btn-group">
                <a href="#" class="btn btn-default">Action 1</a>
                <a href="#" class="btn btn-default">Action 2</a>
                <span class="btn btn-primary btn-file">
                    Browse&hellip; <input type="file" multiple>
                </span>
            </div>
        </div>
        <div class="col-lg-6 col-sm-6 col-12">
            <h4>Input Groups</h4>
            <div class="input-group">
              <span class="input-group-btn">
                <label class="btn btn-primary btn-file" for="multiple_input_group">
                  <div class="input required"><input id="multiple_input_group" type="file" multiple></div> Browse
                </label>
              </span>
              <span class="file-input-label"></span>
            </div>
            <span class="help-block">
                Try selecting one or more files and watch the feedback
            </span>
        </div>
        
    </div>
</div>

                                                          CSS corresponding Codes

.btn-file {
  position: relative;
  overflow: hidden;
}
.btn-file input[type=file] {
  position: absolute;
  top: 0;
  right: 0;
  min-width: 100%;
  min-height: 100%;
  font-size: 100px;
  text-align: right;
  filter: alpha(opacity=0);
  opacity: 0;
  background: red;
  cursor: inherit;
  display: block;
}
.file-input-label {
	padding: 0px 10px;
	display: table-cell;
	vertical-align: middle;
  border: 1px solid #ddd;
  border-radius: 4px;
}
input[readonly] {
  background-color: white !important;
  cursor: text !important;
}

                                 JavaScript Corresponding codes
$(document).on('change', '.btn-file :file', function() {
  var input = $(this),
      numFiles = input.get(0).files ? input.get(0).files.length : 1,
      label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
  input.trigger('fileselect', [numFiles, label]);
});

$(document).ready( function() {
	$('.btn-file :file').on('fileselect', function(event, numFiles, label) {
		console.log("teste");
		var input_label = $(this).closest('.input-group').find('.file-input-label'),
			log = numFiles > 1 ? numFiles + ' files selected' : label;

		if( input_label.length ) {
			input_label.text(log);
		} else {
			if( log ) alert(log);
		}
	});
});

**Comment by AyomiCoder** [comment]
Sir, this is not where the code will be and this is not valid or in line with the project at hand.

**Comment by AyomiCoder** [comment]
Spare some time so that we can review the development level so far.

**Comment by dajyno** [comment]
Have you guys been able to review @AyomiCoder and @exoticmga

**Comment by AyomiCoder** [comment]
I have not heard from him

**Comment by dajyno** [comment]
> I have not heard from him

Please reach out so we don't miss any deadlines
