### ISSUE TITLE
User Dashboard - Frontend

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#21]
Build the profile page/dashboard on the frontend and the splitter interface with few features.

**Comment by dajyno** [comment]
There should be an input

**Comment by AyomiCoder** [comment]
on it boss!

**Comment by AyomiCoder** [comment]
i will love it if you can assign the active frontend devs to this issue. i need active people

**Comment by adeboluuu** [comment]
seen

**Comment by dajyno** [comment]
Any updates guys?

**Comment by AyomiCoder** [comment]
Waiting for chukwuebuka so we can start

**Comment by dajyno** [comment]
What do you need from @trippleme63 ?

Let me know so I can accelerate it

Thanks @AyomiCoder

**Comment by AyomiCoder** [comment]
All the icons and images used in the design and access to the figma. 
@dajyno

**Comment by AyomiCoder** [comment]
@adeboluuu get ready to start work on the dash board.

**Comment by adeboluuu** [comment]
okay @AyomiCoder

**Comment by dajyno** [comment]
> All the icons and images used in the design and access to the figma. 
> @dajyno 

Yes, already assigned the icons to @Queennifer in a separate issue.

**Comment by trippleme63** [comment]
> okay @AyomiCoder
@adeboluuu , How is it going with the dashboard

**Comment by adeboluuu** [comment]
it has been okay so far

**Comment by dajyno** [comment]
Where are we with this please guys?
