### ISSUE TITLE
File Splitting

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#23]
Initiate the splitting of csv and json files in python programmatically, and present the splitted version back to the frontend and finally store it in the database.

**Comment by dajyno** [comment]
A navigation to it should be on the dashboard so users can download later

**Comment by AyomiCoder** [comment]
Nice one Eric

**Comment by exoticmga** [comment]
I will check this out and revert back.

**Comment by dajyno** [comment]
Cheers boss @AyomiCoder 

Thanks @exoticmga , would be waiting for your feedback
