### ISSUE TITLE
Prototypes

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#24]
Prototyping of Landing page, Signup/Sign in modals

**Comment by dajyno** [comment]
Also include the Dashboard and Documentation/FAQ page

**Comment by U-JoJoBear-X** [comment]
We've completed prototyping on the landing page and documentation screen. Next is the dashboard.

**Comment by U-JoJoBear-X** [comment]
The FAQ page is ready too.
you can test the current prototype with this link:
https://www.figma.com/proto/nUnclpNeBdBXMZ7uYS9UCe/Chunkr.iO?node-id=1311%3A1552&scaling=scale-down-width&page-id=1299%3A1086&starting-point-node-id=1311%3A1086&show-proto-sidebar=1

**Comment by dajyno** [comment]
@U-JoJoBear-X Is this link for flow 1 or 2?

**Comment by U-JoJoBear-X** [comment]
It leads you to both so you can navigate between both flows with the side nav

**Comment by dajyno** [comment]
Remember our submitted link is for flow 1....everything should run through there please

**Comment by U-JoJoBear-X** [comment]
Sure thing. Would close flow 2 once I'm done working with it.

**Comment by trippleme63** [comment]
Dashboard prototype should be ready soon. Working on the interactions within the dashboard

**Comment by trippleme63** [comment]
@dajyno , @Agbani123 mentioned to me we you said we needed a profile input modal screen for the  dashboard ?

**Comment by dajyno** [comment]
> @dajyno , @Agbani123 mentioned to me we you said we needed a profile input modal screen for the  dashboard ?
> 
> 

I'm not sure I understand what you mean boss. What is a profile input modal screen please?

**Comment by dajyno** [comment]
@U-JoJoBear-X Nice work on the prototyping so far. 

I noticed that on the Documentation page, when you click on the FAQ section, it scrolls together with the right section. Unlike the others

Check it out

**Comment by U-JoJoBear-X** [comment]
Sure thing. Would check it and give a feedback.

**Comment by U-JoJoBear-X** [comment]
@dajyno I'm sorry but your complaint isn't clear. Please test again and give a feedback.

**Comment by dajyno** [comment]
Ok @U-JoJoBear-X 

Would explain better at our team meeting tonight

**Comment by trippleme63** [comment]
Dashboard ready for prototyping with the homepage. Splitting Screen Checked 👍

**Comment by dajyno** [comment]
Odogwu! 

Nice one boss

**Comment by U-JoJoBear-X** [comment]
I've confirmed that and we've connected it to the landing page and documentation page. It should function now. @trippleme63 do you know if the "Our Team" page is connected too?

**Comment by trippleme63** [comment]
I designed the splitting screen features and components to show the user experience and interactions when splitting a .csv or .json file. 

I encountered problems while designing the splitting components. The splitting component is a drop-down feature that allows users to select the parameter in which they would want to split their file. I realised it is a good user experience that users are limited to split files either by size or by the number of lines for a .csv file and not both at the same time, while for the .json files users have the limitation to split either by size or by the number of files and not both at the same time.

This, led to me designing the prototype to display this valuable user experience. 

Although the problem I encountered was how to make a user experience like this possible in the prototype design, also getting confused sometimes while designing the interactive components of the drop-down feature that allows users select split parameters. It was like getting lost in a maze. 

I did my research and was able to design a prototype with conditions for the users, a splitting parameter must be selected before the user can split and also designed splitting animation loader that shows the splitting process and buttons that appears once splitting is complete requesting the user to "download now" or "save for later". The "save for later" button  takes the user to the recent page on the dashboard while the "download now" button takes the user to the browsers download manager to download the split file in their device.

I prototyped interactions within multiple screens and pages within the dashboard, making use of open overlays, swap overlays interactions, Navigate to and change to interactions. Also designed interactive components to ensure less congestion and an organised workspace.

**Comment by trippleme63** [comment]
> I've confirmed that and we've connected it to the landing page and documentation page. It should function now. @trippleme63 do you know if the "Our Team" page is connected too?

I will check on it

**Comment by U-JoJoBear-X** [comment]
Great work explaining your contribution in detail. I encountered similar challenges and was able to better implement complex components to create a fluid and interactive prototype. These implementations can observed especially on the Documentation page.

Great work once again.

**Comment by dajyno** [comment]
Awesome job guys. Please recheck, the team link isn't active.

All in, excellent delivery!

**Comment by U-JoJoBear-X** [comment]
Here is an updated link for the prototype. @dajyno the issues have been attended to. Please check for review:
https://www.figma.com/proto/SJHloBHOZcsHKdhgqb9qGj/WIP-Chunkr.iO?node-id=1311%3A1086&scaling=min-zoom&page-id=1299%3A1086&starting-point-node-id=1311%3A1086
