### ISSUE TITLE
Exporting Icons

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#27]
Please the development team needs all our icons exported from figma

Export as SVG and put into individual folder for each page. Also name them properly so the dev team can identify them properly.

Due by 10am on 2nd August, 2020

**Comment by AyomiCoder** [comment]
Don't forget to put it in a google drive as a folder. Thanks @Queennifer

**Comment by Queennifer** [comment]
I will @AyomiCoder Already started

**Comment by AyomiCoder** [comment]
@Busybeebee11 you will get the icons and images soon.

**Comment by AyomiCoder** [comment]
Please i need a reply on this @Queennifer

**Comment by dajyno** [comment]
@AyomiCoder it would take a while. Expect them before 10am tomorrow

**Comment by dajyno** [comment]
Also, all our icons used needs to be part of our style guide. 

Please @Foluahiome i would appreciate it if you get on this. Would make this official

**Comment by dajyno** [comment]
@Foluahiome please collate all our icons and input into our style guide. 🙏🏾

**Comment by Busybeebee11** [comment]
Okay. Already got some from @jojobear though.

**Comment by Foluahiome** [comment]
@dajyno Ok noted but i would like to know which icon pack was used to design

**Comment by dajyno** [comment]
@trippleme63 can you specifically which packs your team used for icons? So @Foluahiome can build our style guide

**Comment by Queennifer** [comment]
Done
https://drive.google.com/drive/folders/1cY2nUO-YB8PhwsUjkxA3E-w4pZf489n6?usp=sharing

**Comment by Mariamjeda** [comment]
Google icons and vuessax for the dashboard. I added them to the style guide though

**Comment by trippleme63** [comment]
> @trippleme63 can you specifically which packs your team used for icons? So @Foluahiome can build our style guide

Done 👌

**Comment by Foluahiome** [comment]
Seen, thanks

**Comment by dajyno** [comment]
Welldone with the swiftness of delivery guys.

Keep it up
