### ISSUE TITLE
Research document on chunking

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#30]
We need to research on the coding parameters we would use to achieve the chunking.

Drop your links and research in this document.

https://docs.google.com/document/d/11aM-Slgna-TPKs3tNCEfVNRWzxLRIHECS0f_hSbbKU4/edit?usp=sharing

**Comment by Mamishayde** [comment]
> We need to research on the coding parameters we would use to achieve the chunking.
> 
> Drop your links and research in this document.
> 
> https://docs.google.com/document/d/11aM-Slgna-TPKs3tNCEfVNRWzxLRIHECS0f_hSbbKU4/edit?usp=sharing

Yes Sir!

**Comment by Aadeifee** [comment]
Okay boss

**Comment by Mariamjeda** [comment]
Ok sir

**Comment by dajyno** [comment]
Guys, I haven't gotten any progress report on this.

**Comment by Mariamjeda** [comment]
You will get soon. Looking for stuff that makes sense

**Comment by Mamishayde** [comment]
> Guys, I haven't gotten any progress report on this.

We have already dropped quite a collection of resources in the Google doc file. We only need to be sure that is the direction we are going with our backend.

**Comment by Hillz001** [comment]
Alright work is progresing

**Comment by rhodalewi** [comment]
Dropped some things in the doc. Just need clarification if it is on the right track because I don't understand the language am seeing on google. E dey carry me where I no know

**Comment by Aadeifee** [comment]
There are some links there already

**Comment by U-JoJoBear-X** [comment]
The Google doc is quite resourceful now

**Comment by dajyno** [comment]
Thanks. Over to you @AyomiCoder

**Comment by AyomiCoder** [comment]
Will work on it

**Comment by AyomiCoder** [comment]
Please most of the links contain resources that are not based on Django language. i dont write Go lang or Node Js. 
Thanks.

**Comment by U-JoJoBear-X** [comment]
So you require the ones based on Django?

**Comment by Mariamjeda** [comment]
I put a few on python

**Comment by U-JoJoBear-X** [comment]
We'll update the document based on your newest request now @AyomiCoder

**Comment by Aadeifee** [comment]
I dropped some links that contains how to read csv and json files with pyton

**Comment by Foluahiome** [comment]
Updating the document as per your request

**Comment by Mamishayde** [comment]
Researched for backend development, particularly about carrying files from the front end to the back end using Django and also resources on the process of splitting of files (.slice). The links and research were dropped in the google doc on the issue page.
https://docs.google.com/document/d/11aM-Slgna-TPKs3tNCEfVNRWzxLRIHECS0f_hSbbKU4/edit?usp=sharing

**Comment by Foluahiome** [comment]
@AyomiCoder Please confirm that the added resources are useful

**Comment by Mamishayde** [comment]
Hi @AyomiCoder you might need panda or anaconda
