### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#31]
https://github.com/Busybeebee11/Twitter-Recreate

https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/

These above links would help us write a professional documentation.  Please let's work on this

**Comment by Mariamjeda** [comment]
alright

**Comment by Foluahiome** [comment]
Working on it

**Comment by U-JoJoBear-X** [comment]
Are you referring to the documentation for the readme?

**Comment by Foluahiome** [comment]
> Are you referring to the documentation for the readme?

Yes he is. I have checked other samples and i think we need a few codes to add to the write up we have

**Comment by U-JoJoBear-X** [comment]
We'll have to reach out to Ayomide on that then, the links we'll be adding would be related to the tool usage and I believe he's in the best position to help with that.

**Comment by Foluahiome** [comment]
Ok then

**Comment by dajyno** [comment]
@AyomiCoder we would need to add some codes to this readme file.

Images also

**Comment by Aadeifee** [comment]
Well done guys
