### ISSUE TITLE
Design submission

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#36]
Hey team,
Please go through your prior assigned design tasks, make sure all is as it should be.
We are submitting the final designs today.
Thanks

**Comment by Aadeifee** [comment]
Okay boss…will do that

**Comment by U-JoJoBear-X** [comment]
We've concluded crosschecking the project and have shared it for submission

**Comment by Foluahiome** [comment]
Well done guys

**Comment by Mariamjeda** [comment]
Everything was intact before submission

**Comment by stepha-cell** [comment]
Done

**Comment by trippleme63** [comment]
Co

**Comment by trippleme63** [comment]
Done Already.

**Comment by Queennifer** [comment]
Done!

**Comment by Mamishayde** [comment]
All is in order. Thank you.
