### ISSUE TITLE
Signup/Signin/Reset Password - redesign

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#41]
We need a redesign on the above pages.

We would be removing the modals and making them all into pages.

New design due by 10am, 9th August

**Comment by Foluahiome** [comment]
Ok noted

**Comment by Busybeebee11** [comment]
Work in progress

**Comment by Queennifer** [comment]
@dajyno what screens in particular?

**Comment by Queennifer** [comment]
Oh never mind. no problem

**Comment by Queennifer** [comment]
I've done some designs, but I'm not clear on what you mean by modals, and pages, please

**Comment by stepha-cell** [comment]
Ok, noted

**Comment by Foluahiome** [comment]
> I've done some designs, but I'm not clear on what you mean by modals, and pages, please

It was initially a pop-up modal but because of the Devs we are making it a page. Because of time they need a simple design

**Comment by Foluahiome** [comment]
> Ok, noted. But why are we removing the modals and making it a page?

We are trying to simplify the designs for the Devs

**Comment by Busybeebee11** [comment]
We are having issues connecting the modala to the backend. We left the code
for the modals though, for future use.

**Comment by Foluahiome** [comment]
Pages have been designed
