### ISSUE TITLE
Redesign of Dashboard Pages

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#42]
Please reduce components on the dashboard, make the chunk tool the main page also

Due by 4pm, 9th August

**Comment by Mariamjeda** [comment]
I have redesigned the splitter screens for JSON and CSV. I have also redesigned the profile pop up, the delete confirmation popup and the log out confirmation pop up

**Comment by trippleme63** [comment]
Dashboard redesign accomplished, reducing the development process while still including the user in front and centre of every design decision. 

Link: https://www.figma.com/file/SJHloBHOZcsHKdhgqb9qGj/WIP-Chunkr.iO?node-id=2414%3A5865

**Comment by dajyno** [comment]
I erroneously left out Chidinma from this issue. 

Sorry about that
