### ISSUE TITLE
Signup/Signin modal to pages

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#44]
Going on from the  new designs, please update the frontend to reflect same. ie reflecting the change from modals to full pages

Thanks

**Comment by Busybeebee11** [comment]
Done.

Sign-up, sign-in, forgotten password, and change password pop-up modals
converted to individual pages.

**Comment by Busybeebee11** [comment]
All are fully responsive.

**Comment by dajyno** [comment]
Nice one

**Comment by dajyno** [comment]
@adeboluuu Any updates on the dashboard?

**Comment by adeboluuu** [comment]
i had the old design ready,ill have to make a few modifications
