### ISSUE TITLE
GitHub Documentation

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#46]
Guys, for this thread, please drop any info you have for us to add to our documentation HERE .

Just add a comment underneath and drop what you have so it would be easy for us to collate.

As all designers are done or almost done with design tasks, this is primarily for us. 

@U-JoJoBear-X and myself would collate all we have gathered into a working .md file. **We are not assignees as only 10 persons can be assigned to an issue but rest assured we are part of this task too**

@AyomiCoder please drop in and feel dree to drop comments on our process

**Comment by Mariamjeda** [comment]
1. list of members that worked on the project
2. Something called badges to show some simple stats about the project like the number of forks, contributors, open issues etc...
3. Adding a license. https://choosealicense.com/ can help to choose one.
4. Visual aid of how to use the product. like screen shots or a video
5. Product description eg this product was created to help users manage large json and csv files by helping them to spilt into smaller and easy to use sizes.
django was used as the programming language, mongodb was used for the data base and any other technical lingua Ayo might want to add.
The design aesthetic was mostly minimalist and the 8 point grid system was used.
6. We currently have the ability to split files running. WE hope to be able to give users the ability to share files, to star files/ folders, to view their recent files/ folders all within the platform.

**Comment by Foluahiome** [comment]
7. How to install and run the project
8. Our products unique selling point and what problem it solves
9.  What we learnt during the course of the project
10. Codes used for the implementation

**Comment by Aadeifee** [comment]
11. The largest amount of file I can split? (FAQ)
12. Some of the resources we used for our research

**Comment by Hillz001** [comment]
13. The size of file I can upload
14. Storage capacity for saving files

**Comment by Mamishayde** [comment]
15. The name/logo of Sponsors; Zuri and Ingressive for Good
![image](https://user-images.githubusercontent.com/105178752/183860700-7e14ad46-abe2-4b3f-9c0d-9a635eb36ead.png)

16. A table to show list of designers and developers that worked on the project
17. A chart of the schema, see sample below 
![image](https://user-images.githubusercontent.com/105178752/183859125-856e0263-9e94-4757-8ec9-5d0a12d9f333.png)

18.  We should edit or add to the About tab at the left side bar (the description) to read: Chunk File Project. A tool for easy splitting of large text files.
19. We should also add the tags/topics in the About tab to show our topics like chunk, text-file, json, csv, django, python etc

**Comment by Foluahiome** [comment]
@dajyno Are these helpful?

**Comment by dajyno** [comment]
Yes they are. Would begin working on these today. Thanks A lot

**Comment by dajyno** [comment]
@U-JoJoBear-X can we begin?

**Comment by U-JoJoBear-X** [comment]
Sure thing
