### ISSUE TITLE
Mobile Design - Landing Page

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#51]
Please design the mobile view of the landing page

Use frame - iphone 13 pro

**Comment by Foluahiome** [comment]
@dajyno  You assigned me to design the Teams page

**Comment by Foluahiome** [comment]
@Mamishayde and i are almost done.....do you need me to join the landing page design afterwards?

**Comment by Mamishayde** [comment]
Yes @Foluahiome and I are almost done with the mobile teams page. I used our footer from the mobile teams page on the landing page (consistency)...and the menu drop down.

**Comment by dajyno** [comment]
Sorry about that, I have edited the issue name accordingly.
Please let me know of your progress

**Comment by Foluahiome** [comment]
> Are you sure? I have you on the landing page o

Yes i am and we are done
