### ISSUE TITLE
Mobile Design - Dashboard

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#53]
Please design the mobile view of the Dashboard pages

Use frame - iphone 13 pro

@trippleme63 Please assign individual pages to those assigned here with you.
I already assigned @rhodalewi to the splitting screen and @Queennifer to the profile page

**Comment by trippleme63** [comment]
Dashboard Mobile View has been redesigned effectively.

**Comment by dajyno** [comment]
Excellent work.
Can I close this?
