### ISSUE TITLE
An authenticated Login/Signup system with django REST framework(API)

### ISSUE THREAD

**Issue by AyomiCoder** [zuri-training/Chunk-File-Team-47#7]
A complete login system with authentication and redirections.

**Comment by AyomiCoder** [comment]
Working on this issue

**Comment by exoticmga** [comment]
Ayomide, kindly check the code file I shared the link with you.

**Comment by Beordun** [comment]
Noted.

**Comment by Beordun** [comment]
I’ll push the codes later at night.

**Comment by AyomiCoder** [comment]
Don't forget to create a new branch

**Comment by AyomiCoder** [comment]
Before pushing it, create a new branch so the code base won't be disorganized

**Comment by AyomiCoder** [comment]
You guys should read about Sessions cookies with django
