### ISSUE TITLE
Creating of Style Guides

### ISSUE THREAD

**Issue by dajyno** [zuri-training/Chunk-File-Team-47#9]
[https://www.figma.com/file/nUnclpNeBdBXMZ7uYS9UCe/Chunkr.iO?node-id=21%3A2](url)

Due by 24th of July, 2022

**Comment by Aadeifee** [comment]
The task is completed already

**Comment by Foluahiome** [comment]
Task is completed

**Comment by stepha-cell** [comment]
Task completed

**Comment by dajyno** [comment]
Thank you team. Great job 👏

**Comment by Hillz001** [comment]
Task Completed
